version: "3"

services:

  php:
    build:
      context: .
      target: symfony_php_dev
      args:
        TIMEZONE: ${TIMEZONE}
#    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - .:/var/www/symfony/
    networks:
      - symfony

  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/var/www/symfony/
    networks:
      - symfony
    env_file:
      - docker/.env.nginx
    ports:
      - "80:80"

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - symfony

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mailer:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"   # Interface web
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony:
