controllers:
    resource:
        path: ../src/Infrastructure/Symfony/Controller/API
        namespace: App\Infrastructure\Symfony\Controller\API
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
